apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dittnav-nightly-usage-statistics-reporter
  namespace: personbruker
  labels:
    team: personbruker
spec:
  schedule: 0 1 * * *
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: gpr-credentials
          containers:
            - name: dittnav-nightly-usage-statistics-reporter
              image: {{version}}
              resources:
                requests:
                  memory: 1024Mi
                  cpu: 250m
                limits:
                  memory: 1200Mi
                  cpu: 500m
              volumeMounts:
                - mountPath: /var/run/secrets/nais.io/vault
                  name: vault-secrets
                  subPath: subpath/var/run/secrets/nais.io/vault
                - mountPath: /secret/serviceuser
                  name: vault-secrets
                  subPath: subpath/secret/serviceuser
                - mountPath: /etc/ssl/certs/ca-certificates.crt
                  name: ca-bundle-pem
                  readOnly: true
                  subPath: ca-bundle.pem
                - mountPath: /etc/pki/tls/certs/ca-bundle.crt
                  name: ca-bundle-pem
                  readOnly: true
                  subPath: ca-bundle.pem
                - mountPath: /etc/ssl/ca-bundle.pem
                  name: ca-bundle-pem
                  readOnly: true
                  subPath: ca-bundle.pem
                - mountPath: /etc/pki/tls/cacert.pem
                  name: ca-bundle-pem
                  readOnly: true
                  subPath: ca-bundle.pem
                - mountPath: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
                  name: ca-bundle-pem
                  readOnly: true
                  subPath: ca-bundle.pem
                - mountPath: /etc/ssl/certs/java/cacerts
                  name: ca-bundle-jks
                  readOnly: true
          initContainers:
            - name: vks-init
              image: navikt/vault-sidekick:v0.3.10-d122b16
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "100m"
                limits:
                  memory: "128Mi"
                  cpu: "1000m"
              volumeMounts:
                - mountPath: /var/run/secrets/nais.io/vault
                  name: vault-secrets
                  subPath: subpath/var/run/secrets/nais.io/vault
                - mountPath: /secret/serviceuser
                  name: vault-secrets
                  subPath: subpath/secret/serviceuser
              args:
                - -v=10
                - -logtostderr
                - -vault=https://vault.adeo.no
                - -one-shot
                - -save-token=/var/run/secrets/nais.io/vault/vault_token
                - -cn=secret:serviceuser/data/{{environment}}/srvdn-cache-metrics:dir=/secret/serviceuser,fmt=flatten
                - -cn=secret:kv/{{cluster}}/sbs/dittnav-nightly-usage-statistics-reporter/personbruker:dir=/var/run/secrets/nais.io/vault,fmt=flatten
              env:
                - name: VAULT_AUTH_METHOD
                  value: kubernetes
                - name: VAULT_SIDEKICK_ROLE
                  value: dittnav-nightly-usage-statistics-reporter
                - name: VAULT_K8S_LOGIN_PATH
                  value: auth/kubernetes/{{cluster}}/sbs/login
          serviceAccount: default
          serviceAccountName: default
          volumes:
            - name: vault-secrets
              emptyDir:
                medium: Memory
            - configMap:
                defaultMode: 420
                name: ca-bundle-jks
              name: ca-bundle-jks
            - configMap:
                defaultMode: 420
                name: ca-bundle-pem
              name: ca-bundle-pem
          restartPolicy: Never