apiVersion: batch/v1
kind: Job
metadata:
  name: dittnav-event-cache-metrics-reporter
  namespace: {{namespace}}
  labels:
    team: personbruker
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      containers:
        - name: dittnav-event-cache-metrocs-reporter
          image: {{version}}
          resources:
            requests:
              memory: 1024Mi
              cpu: 250m
            limits:
              memory: 1200Mi
              cpu: 500m
          volumeMounts:
            - mountPath: /var/run/secrets/nais.io/vault
              name: vault-secrets
              subPath: subpath/var/run/secrets/nais.io/vault
            - mountPath: /secret/serviceuser
              name: vault-secrets
              subPath: subpath/secret/serviceuser
      initContainers:
        - name: vks-init
          image: navikt/vault-sidekick:v0.3.10-d122b16
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "1000m"
          volumeMounts:
            - mountPath: /var/run/secrets/nais.io/vault
              name: vault-secrets
              subPath: subpath/var/run/secrets/nais.io/vault
            - mountPath: /secret/serviceuser
              name: vault-secrets
              subPath: subpath/secret/serviceuser
          args:
            - -v=10
            - -logtostderr
            - -vault=https://vault.adeo.no
            - -one-shot
            - -save-token=/var/run/secrets/nais.io/vault/vault_token
            - -cn=secret:kv/{{cluster}}/sbs/dittnav-event-cache-metrics-producer/{{namespace}}:dir=/var/run/secrets/nais.io/vault,fmt=flatten
            - -cn=secret:serviceuser/data/{{environment}}/srvdn-cache-metrics:dir=/secret/serviceuser,fmt=flatten
          env:
            - name: VAULT_AUTH_METHOD
              value: kubernetes
            - name: VAULT_SIDEKICK_ROLE
              value: dittnav-event-cache-metrics-reporter
            - name: VAULT_K8S_LOGIN_PATH
              value: auth/kubernetes/preprod/sbs/login
      volumes:
        - name: vault-secrets
          emptyDir:
            medium: Memory
      restartPolicy: Never
  backoffLimit: 2